# Generated by Django 4.2.8 on 2024-01-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airadio', '0003_remove_advert_advert_type_remove_links_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='advert_type',
            field=models.CharField(blank=True, choices=[('audio', 'Audio'), ('video', 'Video')], max_length=200, null=True, verbose_name='Advert type'),
        ),
        migrations.AddField(
            model_name='links',
            name='content_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'latest'), (2, 'funny'), (3, 'entertainment news'), (4, 'traffic'), (5, 'interview')], default=1, verbose_name='Content type'),
        ),
        migrations.AddField(
            model_name='links',
            name='link_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Content'), (2, 'Branding')], default=1, verbose_name='Link type'),
        ),
        migrations.AddField(
            model_name='reports',
            name='content_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'latest'), (2, 'funny'), (3, 'entertainment news'), (4, 'traffic'), (5, 'interview')], default=1, verbose_name='Content type'),
        ),
        migrations.AddField(
            model_name='reports',
            name='skipped',
            field=models.BooleanField(blank=True, null=True, verbose_name='Skipped'),
        ),
    ]
