# Generated by Django 4.2.8 on 2024-01-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airadio', '0004_advert_advert_type_links_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adverts',
            name='age_group_from',
        ),
        migrations.RemoveField(
            model_name='adverts',
            name='age_group_to',
        ),
        migrations.AddField(
            model_name='adverts',
            name='age_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Teens'), (2, 'P18-34'), (3, 'P25-34'), (4, 'P34-45'), (5, 'P45+')], default=1, verbose_name='Age group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adverts',
            name='microsite',
            field=models.URLField(blank=True, null=True, verbose_name='Microsite URL'),
        ),
    ]
