# Generated by Django 4.2.8 on 2024-01-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airadio', '0005_remove_adverts_age_group_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='mark_clean',
            field=models.BooleanField(default=True, verbose_name='Clean'),
        ),
    ]
