# Generated by Django 4.2.8 on 2024-02-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airadio', '0007_delete_advert_stations_system_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Position Prompt',
                'verbose_name_plural': 'Position Prompts',
                'db_table': 'position_prompts',
            },
        ),
        migrations.CreateModel(
            name='TopicPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Topic Prompt',
                'verbose_name_plural': 'Topic Prompts',
                'db_table': 'topic_prompts',
            },
        ),
    ]
