# Generated by Django 4.2.8 on 2024-02-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airadio', '0009_topicprompts_color_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionprompts',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airadio.stations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicprompts',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airadio.stations'),
            preserve_default=False,
        ),
    ]
