# Generated by Django 4.2.8 on 2024-03-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airadio', '0011_alter_positionprompts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='artistname',
            field=models.CharField(max_length=255, verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
