# Generated by Django 4.2.8 on 2024-04-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airadio", "0012_alter_library_artistname_alter_library_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adverts",
            options={
                "ordering": ["-id"],
                "verbose_name": "Advert",
                "verbose_name_plural": "Adverts",
            },
        ),
    ]
